/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/phemex_futures/json/products.hpp"

using namespace roq;
using namespace roq::phemex_futures;

using namespace std::literals;

// note! reduced
TEST_CASE("simple", "[json_products]") {
  auto message =
      R"({)"
      R"("code":0,)"
      R"("msg":"",)"
      R"("data":{)"
      R"("currencies":[{)"
      R"("currency":"BTC",)"
      R"("name":"Bitcoin",)"
      R"("code":1,)"
      R"("valueScale":8,)"
      R"("minValueEv":1,)"
      R"("maxValueEv":5000000000000000000,)"
      R"("needAddrTag":0,)"
      R"("status":"Listed",)"
      R"("displayCurrency":"BTC",)"
      R"("inAssetsDisplay":1,)"
      R"("perpetual":0,)"
      R"("stableCoin":0,)"
      R"("assetsPrecision":8)"
      R"(},{)"
      R"("currency":"USD",)"
      R"("name":"USD",)"
      R"("code":2,)"
      R"("valueScale":4,)"
      R"("minValueEv":1,)"
      R"("maxValueEv":5000000000000000000,)"
      R"("needAddrTag":0,)"
      R"("status":"Listed",)"
      R"("displayCurrency":"USD",)"
      R"("inAssetsDisplay":1,)"
      R"("perpetual":0,)"
      R"("stableCoin":0,)"
      R"("assetsPrecision":2)"
      R"(},{)"
      R"("currency":"USDT",)"
      R"("name":"TetherUS",)"
      R"("code":3,)"
      R"("valueScale":8,)"
      R"("minValueEv":1,)"
      R"("maxValueEv":5000000000000000000,)"
      R"("needAddrTag":0,)"
      R"("status":"Listed",)"
      R"("displayCurrency":"USDT",)"
      R"("inAssetsDisplay":1,)"
      R"("perpetual":2,)"
      R"("stableCoin":1,)"
      R"("assetsPrecision":8)"
      R"(})"
      R"(],)"
      R"("products":[{)"
      R"("symbol":"BTCUSD",)"
      R"("code":1,)"
      R"("type":"Perpetual",)"
      R"("displaySymbol":"BTC / USD",)"
      R"("indexSymbol":".BTC",)"
      R"("markSymbol":".MBTC",)"
      R"("fundingRateSymbol":".BTCFR",)"
      R"("fundingRate8hSymbol":".BTCFR8H",)"
      R"("contractUnderlyingAssets":"USD",)"
      R"("settleCurrency":"BTC",)"
      R"("quoteCurrency":"USD",)"
      R"("contractSize":1.0,)"
      R"("lotSize":1,)"
      R"("tickSize":0.1,)"
      R"("priceScale":4,)"
      R"("ratioScale":8,)"
      R"("pricePrecision":1,)"
      R"("minPriceEp":100000,)"
      R"("maxPriceEp":10000000000,)"
      R"("maxOrderQty":20000000,)"
      R"("description":"BTC/USD perpetual contracts are priced on the .BTC Index. Each contract is worth 1 USD. Funding fees are paid and received every 8 hours at UTC time: 00:00, 08:00 and 16:00.",)"
      R"("status":"Listed",)"
      R"("tipOrderQty":5000000,)"
      R"("listTime":1574640000000,)"
      R"("majorSymbol":true,)"
      R"("defaultLeverage":"-10",)"
      R"("fundingInterval":28800,)"
      R"("maxLeverage":100,)"
      R"("leverageMargin":1034,)"
      R"("maxOI":-1.0)"
      R"(},)"
      R"({)"
      R"("symbol":"sUSDTTRY",)"
      R"("code":911,)"
      R"("type":"Spot",)"
      R"("displaySymbol":"USDT / TRY",)"
      R"("quoteCurrency":"TRY",)"
      R"("priceScale":4,)"
      R"("ratioScale":8,)"
      R"("pricePrecision":3,)"
      R"("baseCurrency":"USDT",)"
      R"("baseTickSize":"0.001 USDT",)"
      R"("baseTickSizeEv":100000,)"
      R"("quoteTickSize":"0.001 TRY",)"
      R"("quoteTickSizeEv":10,)"
      R"("baseQtyPrecision":3,)"
      R"("quoteQtyPrecision":2,)"
      R"("minOrderValue":"17 TRY",)"
      R"("minOrderValueEv":170000,)"
      R"("maxBaseOrderSize":"500,000 USDT",)"
      R"("maxBaseOrderSizeEv":50000000000000,)"
      R"("maxOrderValue":"500,000 TRY",)"
      R"("maxOrderValueEv":5000000000,)"
      R"("defaultTakerFee":"0.001",)"
      R"("defaultTakerFeeEr":100000,)"
      R"("defaultMakerFee":"0.001",)"
      R"("defaultMakerFeeEr":100000,)"
      R"("description":"USDTTRY is a USDT/TRY spot trading pair. Minimum order value is 17 TRY",)"
      R"("status":"Delisted",)"
      R"("tipOrderQty":100000,)"
      R"("listTime":1660831200000,)"
      R"("ieoOpenPriceEp":0,)"
      R"("ieoInitDurationMs":300000,)"
      R"("buyPriceUpperLimitPct":110,)"
      R"("sellPriceLowerLimitPct":90)"
      R"(})"
      R"(],)"
      R"("perpProductsV2":[{)"
      R"("perpProductSubType":"Normal",)"
      R"("symbol":"BTCUSDC",)"
      R"("code":40041,)"
      R"("type":"PerpetualV2",)"
      R"("displaySymbol":"BTC / USDC",)"
      R"("indexSymbol":".BTCUSDC",)"
      R"("markSymbol":".MBTCUSDC",)"
      R"("fundingRateSymbol":".BTCUSDCFR",)"
      R"("fundingRate8hSymbol":".BTCUSDCFR8H",)"
      R"("contractUnderlyingAssets":"BTC",)"
      R"("settleCurrency":"USDC",)"
      R"("quoteCurrency":"USDC",)"
      R"("tickSize":"0.1",)"
      R"("priceScale":0,)"
      R"("ratioScale":0,)"
      R"("pricePrecision":1,)"
      R"("baseCurrency":"BTC",)"
      R"("description":"BTC/USDC perpetual contracts are priced on the .BTCUSDC Index. Each contract is worth 1 BTC. Funding fees are paid and received every 8 hours at UTC time: 00:00, 08:00 and 16:00.",)"
      R"("status":"Listed",)"
      R"("tipOrderQty":0,)"
      R"("listTime":1747735200000,)"
      R"("majorSymbol":true,)"
      R"("defaultLeverage":"-10",)"
      R"("fundingInterval":28800,)"
      R"("maxLeverage":100,)"
      R"("leverageMargin":1002,)"
      R"("maxOI":-1.0,)"
      R"("maxOrderQtyRq":"1000",)"
      R"("maxPriceRp":"500000",)"
      R"("minOrderValueRv":"1",)"
      R"("minPriceRp":"1000",)"
      R"("qtyPrecision":4,)"
      R"("qtyStepSize":"0.0001",)"
      R"("tipOrderQtyRq":"200",)"
      R"("maxOpenPosLeverage":100.0)"
      R"(})"
      R"(],)"
      R"("perpProductsPilot":null,)"
      R"("riskLimits":[{)"
      R"("symbol":"BTCUSD",)"
      R"("steps":"0",)"
      R"("riskLimits":[{"limit":1500,"initialMargin":"10.0%","initialMarginEr":10000000,"maintenanceMargin":"5.0%","maintenanceMarginEr":5000000}])"
      R"(})"
      R"(],)"
      R"("leverages":[{)"
      R"("initialMargin":"1.0%",)"
      R"("initialMarginEr":1000000,)"
      R"("options":[1.0,2.0,3.0,5.0,10.0,25.0,50.0,100.0])"
      R"(})"
      R"(],)"
      R"("riskLimitsV2":[{)"
      R"("symbol":"BTCUSDT",)"
      R"("steps":"0K",)"
      R"("riskLimits":[{"limit":2000000,"initialMarginRr":"0.01","maintenanceMarginRr":"0.005"}])"
      R"(})"
      R"(],)"
      R"("leveragesV2":[{)"
      R"("options":[1.0,2.0,3.0,5.0,10.0,25.0,50.0,100.0],)"
      R"("initialMarginRr":"0.01")"
      R"(})"
      R"(],)"
      R"("leverageMargins":[{)"
      R"("index_id":1,)"
      R"("items":[{"notionalValueRv":50000,"maxLeverage":20.0,"maintenanceMarginRateRr":"0.01","maintenanceAmountRv":"0"})"
      R"(])"
      R"(})"
      R"(],)"
      R"("ratioScale":8,)"
      R"("md5Checksum":"3e137ae32b5f8807e2e7b7a61a85be13")"
      R"(})"
      R"(})";
  core::json::BufferStack buffer{65536, 2};
  [[maybe_unused]] json::Products obj{message, buffer};
}
