/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/phemex_futures/json/account_positions.hpp"

using namespace roq;
using namespace roq::phemex_futures;

using namespace std::literals;

TEST_CASE("simple", "[json_account_positions]") {
  auto message = R"({)"
                 R"("code":0,)"
                 R"("msg":"",)"
                 R"("data":{)"
                 R"("account":{)"
                 R"("userID":8860688,)"
                 R"("accountId":88606880001,)"
                 R"("currency":"BTC",)"
                 R"("accountBalanceEv":50649,)"
                 R"("totalUsedBalanceEv":0,)"
                 R"("bonusBalanceEv":0)"
                 R"(},)"
                 R"("positions":[{)"
                 R"("userID":8860688,)"
                 R"("accountID":88606880001,)"
                 R"("symbol":"BTCUSD",)"
                 R"("currency":"BTC",)"
                 R"("side":"None",)"
                 R"("positionStatus":"Normal",)"
                 R"("crossMargin":false,)"
                 R"("leverageEr":-1000000000,)"
                 R"("leverage":-10.00000000,)"
                 R"("initMarginReqEr":10000000,)"
                 R"("initMarginReq":0.10000000,)"
                 R"("maintMarginReqEr":500000,)"
                 R"("maintMarginReq":0.00500000,)"
                 R"("riskLimitEv":150000000000,)"
                 R"("riskLimit":1500.00000000,)"
                 R"("size":0,)"
                 R"("value":0E-8,)"
                 R"("valueEv":0,)"
                 R"("avgEntryPriceEp":0,)"
                 R"("avgEntryPrice":0E-8,)"
                 R"("posCostEv":0,)"
                 R"("posCost":0E-8,)"
                 R"("assignedPosBalanceEv":0,)"
                 R"("assignedPosBalance":0E-8,)"
                 R"("bankruptCommEv":0,)"
                 R"("bankruptComm":0E-8,)"
                 R"("bankruptPriceEp":0,)"
                 R"("bankruptPrice":0E-8,)"
                 R"("positionMarginEv":0,)"
                 R"("positionMargin":0E-8,)"
                 R"("liquidationPriceEp":0,)"
                 R"("liquidationPrice":0E-8,)"
                 R"("deleveragePercentileEr":0,)"
                 R"("deleveragePercentile":0E-8,)"
                 R"("buyValueToCostEr":10126000,)"
                 R"("buyValueToCost":0.10126000,)"
                 R"("sellValueToCostEr":10114000,)"
                 R"("sellValueToCost":0.10114000,)"
                 R"("markPriceEp":992560065,)"
                 R"("markPrice":99256.00650000,)"
                 R"("estimatedOrdLossEv":0,)"
                 R"("estimatedOrdLoss":0E-8,)"
                 R"("usedBalanceEv":0,)"
                 R"("usedBalance":0E-8,)"
                 R"("cumClosedPnlEv":0,)"
                 R"("cumFundingFeeEv":0,)"
                 R"("cumTransactFeeEv":0,)"
                 R"("transactTimeNs":1763251200001180845,)"
                 R"("takerFeeRateEr":-100000000,)"
                 R"("makerFeeRateEr":-100000000,)"
                 R"("term":1,)"
                 R"("lastTermEndTimeNs":0,)"
                 R"("lastFundingTimeNs":1763251200000000000,)"
                 R"("curTermRealisedPnlEv":0,)"
                 R"("execSeq":20787917579,)"
                 R"("freeQty":0,)"
                 R"("freeCostEv":0,)"
                 R"("buyLeavesValueEv":0,)"
                 R"("sellLeavesValueEv":0,)"
                 R"("buyLeavesQty":0,)"
                 R"("sellLeavesQty":0)"
                 R"(})"
                 R"(])"
                 R"(})"
                 R"(})";
  core::json::BufferStack buffers{8192, 3};
  [[maybe_unused]] json::AccountPositions obj{message, buffers};
}
