/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/phemex/json/instruments.hpp"

using namespace roq;
using namespace roq::phemex;

using namespace std::literals;

// note! reduced
TEST_CASE("simple", "[json_instruments]") {
  auto message = R"({)"
                 R"("code":"00000",)"
                 R"("msg":"success",)"
                 R"("requestTime":1758094735513,)"
                 R"("data":[{)"
                 R"("symbol":"BTCUSDT",)"
                 R"("category":"USDT-FUTURES",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USDT",)"
                 R"("buyLimitPriceRatio":"0.05",)"
                 R"("sellLimitPriceRatio":"0.05",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("minOrderQty":"0.0001",)"
                 R"("maxOrderQty":"1200",)"
                 R"("pricePrecision":"1",)"
                 R"("quantityPrecision":"4",)"
                 R"("quotePrecision":"",)"
                 R"("priceMultiplier":"0.1",)"
                 R"("quantityMultiplier":"0.0001",)"
                 R"("type":"perpetual",)"
                 R"("minOrderAmount":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("status":"online",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"",)"
                 R"("deliveryStartTime":"",)"
                 R"("deliveryPeriod":"",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"8",)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"125",)"
                 R"("maintainTime":"",)"
                 R"("maxMarketOrderQty":"220")"
                 R"(},{)"
                 R"("symbol":"ETHUSDT",)"
                 R"("category":"USDT-FUTURES",)"
                 R"("baseCoin":"ETH",)"
                 R"("quoteCoin":"USDT",)"
                 R"("buyLimitPriceRatio":"0.05",)"
                 R"("sellLimitPriceRatio":"0.05",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("minOrderQty":"0.01",)"
                 R"("maxOrderQty":"9900",)"
                 R"("pricePrecision":"2",)"
                 R"("quantityPrecision":"2",)"
                 R"("quotePrecision":"",)"
                 R"("priceMultiplier":"0.01",)"
                 R"("quantityMultiplier":"0.01",)"
                 R"("type":"perpetual",)"
                 R"("minOrderAmount":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("status":"online",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"",)"
                 R"("deliveryStartTime":"",)"
                 R"("deliveryPeriod":"",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"8",)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"100",)"
                 R"("maintainTime":"",)"
                 R"("maxMarketOrderQty":"1900")"
                 R"(},{)"
                 R"("symbol":"PORTALSUSDT",)"
                 R"("category":"USDT-FUTURES",)"
                 R"("baseCoin":"PORTALS",)"
                 R"("quoteCoin":"USDT",)"
                 R"("buyLimitPriceRatio":"0.15",)"
                 R"("sellLimitPriceRatio":"0.15",)"
                 R"("feeRateUpRatio":"0.005",)"
                 R"("makerFeeRate":"0.0002",)"
                 R"("takerFeeRate":"0.0006",)"
                 R"("openCostUpRatio":"0.01",)"
                 R"("minOrderQty":"1",)"
                 R"("maxOrderQty":"2000000",)"
                 R"("pricePrecision":"5",)"
                 R"("quantityPrecision":"0",)"
                 R"("quotePrecision":"",)"
                 R"("priceMultiplier":"0.00001",)"
                 R"("quantityMultiplier":"1",)"
                 R"("type":"perpetual",)"
                 R"("minOrderAmount":"5",)"
                 R"("maxSymbolOrderNum":"200",)"
                 R"("maxProductOrderNum":"1000",)"
                 R"("maxPositionNum":"150",)"
                 R"("status":"online",)"
                 R"("offTime":"-1",)"
                 R"("limitOpenTime":"-1",)"
                 R"("deliveryTime":"",)"
                 R"("deliveryStartTime":"",)"
                 R"("deliveryPeriod":"",)"
                 R"("launchTime":"",)"
                 R"("fundInterval":"4",)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"20",)"
                 R"("maintainTime":"",)"
                 R"("maxMarketOrderQty":"200000")"
                 R"(})"
                 R"(])"
                 R"(})"
                 R"(})";
  core::json::BufferStack buffer{8192, 1};
  [[maybe_unused]] json::Instruments obj{message, buffer};
}
